auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

memberlist:
  join_members:
    - loki-read
    - loki-write
    - loki-backend
  bind_port: 7946

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: memberlist
  storage:
    s3:
      endpoint: http://minio:9000
      insecure: true
      access_key_id: loki
      secret_access_key: supersecret
      bucketnames: loki-data
      s3forcepathstyle: true
  compactor_address: http://loki-backend:3100

schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  storage:
    type: s3
    s3:
      bucketnames: loki-ruler
      endpoint: http://minio:9000
      access_key_id: loki
      secret_access_key: supersecret
      insecure: true

compactor:
  working_directory: /tmp/compactor

limits_config:
  retention_period: 168h
