global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'alloy'
    static_configs:
      - targets: ['alloy:12345']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
